# Generated by Django 4.2.2 on 2023-06-24 06:21

import django.core.validators
from django.db import migrations, models
import exam_240623.fruitipedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitipedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), exam_240623.fruitipedia.models.only_letters_validator])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField()),
            ],
        ),
    ]
